/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
    HoverContainer: typeof import('./../components/common/hover-container.vue')['default']
    IconLocalAvatar: typeof import('~icons/local/avatar')['default']
    IconLocalLogo: typeof import('~icons/local/logo')['default']
    IconLocalLogoFill: typeof import('~icons/local/logo-fill')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NMenu: typeof import('naive-ui')['NMenu']
    NTooltip: typeof import('naive-ui')['NTooltip']
    SharedSubtitle: typeof import('./../components/custom/shared-subtitle.vue')['default']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
  }
}
